README.md, ob-async.el, ob-async.org, test/ob-async-test.el, test/test-helper.el
This fixes #10 and #11. It's essentially what I discuss in #10. `org-babel-execute-src-block` is advised with the ob-async function when the ob-async package is loaded. If the block being executed does not have an `:async` parameter, then the unadvised `org-babel-execute-src-block` is called. To preserve backwards compatibility with the `org-ctrl-c-ctrl-c-hook`, if the ob-async function is invoked not as advice, then it gives a warning and does nothing, which allows `org-babel-execute-src-block` to get executed instead during ctrl-c-ctrl-c, rerunning the async function as advice, and allowing asynchronous execution to take place.
There's a new test case for the `#+NAME` use case, one for the `#+CALL` use case, and one with `org-ctrl-c-ctrl-c-hook` set as well. 
One caveat worth …
=> Advise all babel executions for #+NAME and #+CALL use cases

.travis.yml, Makefile
Cask was using Emacs 24.3, but `add-advice` wasn't added until Emacs 24.4. The fact that we were using Emacs 24.3 was a mistake. Setting the Emacs version explicitly in the invocation of Cask fixes the build.
=> Set Emacs version for Cask to fix tests

ob-async.el, ob-async.org, test/ob-async-test.el
If `org-confirm-babel-evaluate` is non-nil, we should wait for
confirmation before inserting a #+RESULTS block.
Addresses https://github.com/astahlman/ob-async/issues/23
=> Confirm evaluation before inserting RESULTS block

Cask, ob-async.el, ob-async.org
We've been using the `-if-let` macro from dash.el without every
explicitly requiring the dash library. dash is a common library, so
we've gotten away with it until now - see [1].
[1] https://github.com/astahlman/ob-async/issues/25
=> Add explicit dependency on dash

ob-async.el, ob-async.org
Ensure that the `load-path` used in the async child process matches the
`load-path` in the parent process. I suspect that this is the root cause
of issues like https://github.com/astahlman/ob-async/issues/19 and
https://github.com/astahlman/ob-async/issues/21.
=> Make child process inherit load-path from parent

troubleshooting.org
See https://github.com/astahlman/ob-async/issues/21, in which the
subprocess was not able to find the function `org-babel-execute:sql`
because `sql` had never been added to `org-babel-load-languages` (in the
parent process).
I've added a new checklist entry in troubleshooting.org to help diagnose
this type of problem by printing the list of languages defined in
`org-babel-load-languages`.
=> Check load-languages in troubleshooting guide

ob-async.el
Currently when updating the results buffer the user might get
surprised if they are in the middle of typing. This is because using
switch-to-buffer will interfere with interactive typing, as the
documentation notes:
WARNING: This is NOT the way to work on another buffer temporarily
within a Lisp program!
Rather than using set-buffer though we can simply use
the (with-current-buffer) wrapper. This also means we don't need the
register hack to save our position. The user will still see the "Code
block evaluation complete." message appear in the miibuffer but we
could make a cleaner message. This is left as an exercise for a later
patch.
Signed-off-by: Alex Bennée <alex.bennee@linaro.org>
=> ob-async: use with-current-buffer to update org buffer

ob-async.el, test/ob-async-test.el
I recently noticed an incompatibility between this and the [`ob-ipython` package](https://github.com/gregsexton/ob-ipython), which defines its own `:async` keyword (and keeps an open pipe to an ipython session running in the background). To remedy this, I have added an elisp variable `ob-async-no-async-languages-alist` here: for any languages included in this list, the original `ctrl-c-ctrl-c` function is run — as it is for src blocks that do not include the `:async` keyword. By default, the variable is set to `nil`, so that there are no changes to the default behavior of `ob-ipython`.
I've also included a test to show this functionality in action. By setting `ob-async-no-async-languages-alist` to `'("sh")`, we can run one of the core tests, but expect that the code will finish before the …
=> Add list of languages for ob-async to ignore

troubleshooting.org
We no longer use the org-ctrl-c-ctrl-c-hook, so this check isn't
needed.
=> Remove check for ctrl-c ctrl-c hook

README.md, ob-async.el, test/ob-async-test.el
Add a hook that runs before the src block is executed. This hook enables users to perform package-specific initialization that would normally be handled in `init.el`. See https://github.com/astahlman/ob-async/issues/37 for a motivating example.
=> Add a pre-execute hook

ob-async.el, test/ob-async-test.el
`default-directory` was bound when we evaluated the src-block, but not
in the results callback.
One situation where this caused problems was when both :dir and :file
are set in the headers. We *should* resolve :file relative to :dir,
but we were actually resolving :file relative to the buffer-local
value of `default-directory`.
The new unit test covers this scenario (reported in [1])
[1] https://github.com/astahlman/ob-async/issues/44
=> Ensure default-directory is set in results callback

test/ob-async-test.el
This test case was using `print`, which produces a syntax error if the
default system Python interpreter is python3. `print()` should
work for both python2 and python3.
=> Make test case work with python 2 and 3

ob-async.el, test/ob-async-test.el
The function `org-babel-insert-result` assumes that point is on the SRC_BLOCK that we are executing. This wasn't true, in our case - we were inserting/overwriting the RESULTS block with a placeholder GUID, then searching for the GUID in our results callback and putting point on the RESULTS block. This causes problems in some corner-cases, e.g., named SRC_BLOCKS with spaces in the names (see [1]).
Instead of marking our place in the buffer with a GUID, we can simplify thing by leaving ourselves a marker. We already know the location of the current SRC_BLOCK when we start execution - we just need to keep a reference to it in our callback function.
The GUID that we insert into the results block is serving no purpose now, so we could remove it or replace it with a more informative message. …
=> Use marker to keep track of src_block

ob-async.el, test/ob-async-test.el
Stop sleeping for a fixed amount of time in our test cases while we
wait for results. Instead, add a macro that allows us to run code at
two points in time:
1. Immediately after executing `ctrl-c-ctrl-c`
2. After the src-block is done executing
The tests now run in roughly half the time that they took previously.
=> Use callbacks instead of fixed sleep in test cases 

.travis.yml
Emacs 25 is no longer in pre-release. Also, Emacs 26 is out, so let's
test against that, too.
=> Test against Emacs 25 and 26

ob-async.el, test/ob-async-test.el
With that PR code blocks with the option `:results: none` or `:results silent` are handled correctly.
=> Really hide result block when result-params contains "none"

test/ob-async-test.el
We have a couple of tests that ostensibly write a string to "/tmp/foo",
but neither of them deletes the file on setup or teardown. If one of
them fails, the success of the other test could mask it.
Ideally the file would be named with a GUID and we'd clean it up after
each test case, but I'll leave that as a future improvement.
=> Name temp files according to test case

ob-async.el, test/ob-async-test.el
See https://github.com/astahlman/ob-async/issues/65 for a motivating
example. The user (reasonably) expects that setting
`org-babel-python-command` will take effect in an :async src_block, but
it doesn't unless you set this value in the subprocess with a
pre-execute hook, i.e.,
```emacs-lisp
(add-hook 'ob-async-pre-execute-src-block-hook
'(lambda ()
(setq org-babel-python-command "python3")))
```
Instead of requiring the user to recreate the calling context in the
subprocess by setting variables in an
`ob-async-pre-execute-src-block-hook`, now we will automatically inherit
the values of any variables whose name begins with "org-babel-" in the
async subprocess.
=> Inherit any variables prefixed with "org-babel-"

test/ob-async-test.el
This test occasionally passes - no idea why, but don't have the energy
to look into it given that Emacs 24 is several years old.
=> Disable flaky test on Emacs 24

troubleshooting.org
Add a step to check that running a vanilla elisp function via the
emacs-async library works. If this step fails, the user likely has
problems that have nothing to do with org and/or ob-async.
=> Check that vanilla async works in troubleshooting.org
